CREATE
OR REPLACE VIEW REPRESENTATION AS
SELECT TOR.NAME
     , MIN(CHILDTORRENT.SEED_TIME)                     as seed_time
     , COUNT(DISTINCT CHILDTORRENT.ID)                 as child_torrent_count
     , ARRAY_AGG(DISTINCT CHILDTRACKER.NAME)           as child_tracker_names
     , ARRAY_AGG(DISTINCT CHILDTORRENT.TRANSMISSION_ID)as child_torrent_transmission_ids
     , MAX(FI.HARD_LINKS)                              as hardlinks
FROM TORRENT TOR
         LEFT OUTER JOIN TRACKER TR ON TOR.ID = TR.TORRENT_ID
         LEFT OUTER JOIN FILE_ITEM_OCCURRENCE FIO ON TOR.ID = FIO.TORRENT_ID
         LEFT OUTER JOIN FILE_ITEM FI ON FIO.FILE_ITEM_PATH = FI.PATH
         LEFT OUTER JOIN FILE_ITEM_OCCURRENCE CHILDFIO ON FI.PATH = CHILDFIO.FILE_ITEM_PATH
         LEFT OUTER JOIN TORRENT CHILDTORRENT ON CHILDTORRENT.ID = CHILDFIO.TORRENT_ID
         LEFT OUTER JOIN TRACKER CHILDTRACKER ON CHILDTORRENT.ID = CHILDTRACKER.TORRENT_ID
GROUP BY TOR.NAME
ORDER BY MIN(TOR.SEED_TIME) DESC;