
name: Java Jib with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: JIB container build and publish
        uses: MathieuSoysal/jib-container-publish.yml@v2.1.4
        with:
          # Use docker.io for Docker Hub if empty
          REGISTRY: registry.hub.docker.com
          # github.repository as <your-account>/<your-repo>
          IMAGE_NAME: ghostwritertje/nuclearr
          # Tag name of the image to publish
          tag-name: ${{ github.event.release.tag_name }}
          # Username to login to registry
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          # Password to login to registry
          java-version: 17
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
